### ISSUE TITLE
Errors while provisionning

### ISSUE THREAD

**Issue by tedd77** [FrostbyteGR/RouterSCRIPTS#1]
Hell,
Thank you for the scripts.
I tried to apply them on my CCR-1036 with version 45.6
Errors when doing $provision auto
Despite the fact that I renamed the dist.cfg into my router identity name and fully populated the 4 sections in there, it is still giving the following errors:

[Provision][Info]: Provisioning all available modules.
[Provision][Info]: Provisioning gateways.
[Provision][Error]: The configuration variable WANNames cannot be left empty or contain an invalid value.
[Provision][Error]: The configuration variable WANGateways cannot be left empty or contain an invalid value.
[Provision][Error]: The configuration variable WANGatewayPrefix cannot be left empty or contain an invalid value.
[Provision][Error]: The configuration variable BalancingRulePrefix cannot be left empty or contain an invalid value.
[Provision][Error]: The gateways configuration is invalid, please check the config file and try again.
[Provision][Info]: Provisioning failover.
[Provision][Error]: The failover module depends on the gateway selector module, please provision it and try again.
[Provision][Info]: incorrect arguments, try:
$provision auto|purge|failover|gateways|dyndns|resolver|livestream
[Provision][Info]: incorrect arguments, try:
$provision auto|purge|failover|gateways|dyndns|resolver|livestream
[Provision][Info]: Provisioning livestream.
[Provision][Error]: The configuration variable LVStreamList cannot be left empty or contain an invalid value.
[Provision][Error]: The configuration variable LVStreamFQDN cannot be left empty or contain an invalid value.
[Provision][Error]: The configuration variable LVStreamRulePrefix cannot be left empty or contain an invalid value.
[Provision][Error]: The livestream configuration is invalid, please check the config file and try again.
[Provision][Error]: Completed with errors.

-----
Kindly assist in solving this issue or point me to where my mistake is.

Best regards

**Comment by FrostbyteGR** [comment]
If you're editing the configuration file with Notepad++ make sure that every line ends with a carriage return along with a line feed (\r\n). You can do so by hitting _Edit -> EOL Conversion -> Windows (CR LF)_.

Documentation will be updated with this information as soon as I find the time to do so (or I will improve the parser to detect it and adjust accordingly).
